### ISSUE TITLE
Feature: Add compatibility for Storybook 8

### ISSUE THREAD

**Issue by brandonroberts** [brandonroberts/angular-v17-vite-storybook#7] opened 2024-04-26 14:14 UTC
Storybook 8 has introduced the idea of `frameworks` and is not able to run Storybook directly with the `@storybook/angular` package as the framework.

We should figure out if there is a way to make this compatible.

**Comment by brandonroberts** [comment] 2024-04-26 14:43
It looks like as long as we keep the `core.builder.name` as `@storybook/builder-vite` in the `.storybook/main.ts`, things still work with Storybook 8.

**Comment by RyanClementsHax** [comment] 2024-04-26 20:47
You can assign this to me

**Comment by RyanClementsHax** [comment] 2024-04-29 20:42
What is the issue you're seeing exactly? This is working for me locally.

Were you looking to package this as a storybook framework?

**Comment by brandonroberts** [comment] 2024-04-30 18:07
It was mainly testing the upgrade to Storybook 8 to see if we could continue using the `@storybook/builder-vite` with the `@storybook/angular` framework package.

**Comment by brandonroberts** [comment] 2024-05-02 16:55
If it makes the setup easier, sure. I don't know anything about addons 🙃

**Comment by RyanClementsHax** [comment] 2024-05-02 17:02
Yeah it can hide all of that configuration so the final config can look like this.

```ts
const config = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  framework: {
    name: "@storybook/analog", // 👈 This line hides everything
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};

export default config;
```

It also makes it easier to change the way analog wraps vite since you don't have projects depending upon the specifics of how analog works.

**Comment by brandonroberts** [comment] 2024-05-02 17:19
I see. I'd rather not create a separate framework if possible because `@storybook/angular` contains all the utilities for it and maybe some extra setup underneath, but just allow people to use the plugin as is in case they need to configure it more.

**Comment by valentinpalkovic** [comment] 2024-05-02 18:47
I also don't think a separate framework would be a good idea since the whole mounting part had to be re-implemented. Also, the decorators for mocking providers, services, directives etc. would need to be copied over. 

It seems setting `@storybook/builder-vite` via `core.builder.name` seems to work.

Now, we would have to make sure the following things are working:

- Users will run Storybook via the angular builder, which @storybook/angular provides. This makes sure that multiple Storybooks can be configured for multiple Angular libs and applications in the same repository, for example if nx is managing multiple apps.
- The options, like the options for compodoc or other options like assets, styles, ... have to be respected if they are set as builder options. Just setting the builder to `@storybook/builder-vite` will not tell the analog bite plug-in which styles and other builder related options should be applied.
- we can release an experimental support of cite via a feature flag after the above mentioned things are implemented. This requires more or less to provide a `viteFinal` preset in @storybook/angular to configure the analog vite plugin and to pass the required builder options to the plugin, if it's option interface allows it!

I can give a short walkthrough about how the webpack5 implementation works and which kind of things has to be considered to that the bite equivalent would work similarly.

**Comment by RyanClementsHax** [comment] 2024-05-02 22:22
That makes sense. Assuming the angular framework can build using the vite builder, would you suggest using an add on to package extra analog specific configuration or would you suggest this be pre-configured in the angular framework?

**Comment by valentinpalkovic** [comment] 2024-05-03 05:10
This is a good question. I think for convenience reasons it's better to pre-configure the Vite stuff in @storybook/angular. On the other side, this will increase the download size of @storybook/angular. 

For now, I am not concerned that much about the increased size, but I would like to make it as easy as possible to switch to the Vitr builder.

**Comment by RyanClementsHax** [comment] 2024-05-04 15:34
Since analog's relationship with angular is like that between nuxt and vue, I took a look at how they do it. [@storybook-vue/nuxt](https://github.com/storybook-vue/storybook-nuxt/) wraps around `@storybook/vue3-vite` to allow storybook to understand nuxt conventions without reimplementing storybook's vue renderer.

As analog evolves, analog-specific components and patterns will evolve on top of the specific build config like nuxt. I'm thinking we could take a similar approach.

What do y'all think?

**Comment by valentinpalkovic** [comment] 2024-05-04 17:01
This makes total sense to me, if you see the issue from a meta framework perspective.

Let me give you some context:
The main goal (for now) is to support a faster builder (Vite) for Angular. I have experimented with an esbuild builder in the past to build Storybook and to use Vite to run the dev server, which then utilizes Angular's esbuild setup. I stuck or haven't continued on the custom vite server setup, which Angular uses to build their application and to somehow adapt it for Storybook.

At some point @brandonroberts came around and suggested to use his vite plugin, which is also used for Analog.

The main idea now is to use this Vite plugin to provide the possibility of using Vite instead of Webpack to build Storybook for Angular applications. We haven't talked about any Analog support so far. Indeed, if the community wishes Analag support, a complete separate @storybook/analog framework package would make total sense. This isn't my primary goal for now. The first step would be to provide a Webpsck5 alternative. Having a separate package would allow us to optimize for analog-specific topics, but I don't want to switch normal Angular users to a @storybook/analog packages if they only would like to use Vitr as a builder.

Does that make sense?

**Comment by RyanClementsHax** [comment] 2024-05-06 21:56
Oh I see what you're saying. I was focused on wrapping analog specific features in a framework whereas you were talking about stabilizing `@storybook/angular`'s vite support. We are in agreement.

**Comment by RyanClementsHax** [comment] 2024-05-07 14:29
@brandonroberts what do you think of having a section on the analog docs explaining how to get analog and storybook to work well together for now, but mark it as unstable until `@storybook/angular` stabilizes vite support? Another option would be to link to a github issue if we think the "current state of advice" would change frequently.

**Comment by brandonroberts** [comment] 2024-05-07 16:12
Yes, I think that's what we should start with. A guide for the docs in the integration section showing you how to use Storybook and Angular with Vite instead of Webpack. We can link back to the original issue also.

**Comment by RyanClementsHax** [comment] 2024-05-07 20:54
I'd be happy to make that change for you.

**Comment by brandonroberts** [comment] 2024-05-07 22:00
🤝

**Comment by RyanClementsHax** [comment] 2024-05-18 18:04
I haven't forgotten about this. I'm testing the ionic part of the docs for mantis and will commit any helpful changes to analog's docs upstream. I'll handle this afterwards. The hang up is with the interaction between ionic and vitest.

**Comment by RyanClementsHax** [comment] 2024-06-11 19:52
Same update as before. I thought integrating Mantis with Ionic would be easy, but I was wrong. I'll circle back on this and get something up soon.

**Comment by brandonroberts** [comment] 2024-06-11 20:02
No problem. Anything from our end that would help?

**Comment by RyanClementsHax** [comment] 2024-06-11 21:52
Let me get back to you on that. I'm away from my computer for the day but should be returning to this project sometime this week. I'll keep you aprised.

**Comment by RyanClementsHax** [comment] 2024-06-15 13:48
Ok. The problem I'm facing is best summarized by this issue I brought up with an analog/ionic template https://github.com/eduardoRoth/analog-ionic-capacitor-template/issues/2. I've also reproduced this in a mantis repo. https://github.com/RyanClementsHax/nx-storybook-repro/tree/ionic-analog.

I'm having trouble getting Vitest to work with ionic's packages. It's complaining about ESM/CJS problems.

This seems to be an issue previously encountered https://github.com/ionic-team/ionic-framework/issues/25104, but other people are having issues with the angular package https://forum.ionicframework.com/t/i-cant-manage-to-make-vitest-work-with-a-new-standalone-ionic-angular-project/240892 like us.

I've been trying to solve this issue with various vitest configs for the past two months worth of free time  and I should probably start asking for help  lol 😅.

Would you happen to have an idea of what's going on here? I'll be happy to move this to a separate forum if you'd like.

As promised I'll get the docs updated for storybook. Thanks for your patience.

**Comment by codexshell** [comment] 2024-06-16 00:43
Hello, fellow contributors, I know this is probably not the place but I'd like to request for a co-contributor/reviewer for the particular project. Integrating `Angular` into `Turborepo` and collectively into the `Vercel` ecosystem. Thank you for your time an attention.

[`feat(examples): add example-with-angular #8140`](https://github.com/vercel/turbo/pull/8140)

**Comment by brandonroberts** [comment] 2024-06-17 16:28
> Ok. The problem I'm facing is best summarized by this issue I brought up with an analog/ionic template [eduardoRoth/analog-ionic-capacitor-template#2](https://github.com/eduardoRoth/analog-ionic-capacitor-template/issues/2). I've also reproduced this in a mantis repo. https://github.com/RyanClementsHax/nx-storybook-repro/tree/ionic-analog.
> 
> I'm having trouble getting Vitest to work with ionic's packages. It's complaining about ESM/CJS problems.
> 
> This seems to be an issue previously encountered [ionic-team/ionic-framework#25104](https://github.com/ionic-team/ionic-framework/issues/25104), but other people are having issues with the angular package https://forum.ionicframework.com/t/i-cant-manage-to-make-vitest-work-with-a-new-standalone-ionic-angular-project/240892 like us.
> 
> I've been trying to solve this issue with various vitest configs for the past two months worth of free time and I should probably start asking for help lol 😅.
> 
> Would you happen to have an idea of what's going on here? I'll be happy to move this to a separate forum if you'd like.
> 
> As promised I'll get the docs updated for storybook. Thanks for your patience.

Answered in the forum https://forum.ionicframework.com/t/i-cant-manage-to-make-vitest-work-with-a-new-standalone-ionic-angular-project/240892/2?u=brandonroberts

**Comment by brandonroberts** [comment] 2024-06-17 17:22
One interesting thing is that anything included in `ssr.noExternal` should get inlined for Vitest also, but maybe it doesn't support glob patterns 🤔 

```ts
defineConfig(({ mode }) => ({
  ssr: {
    noExternal: [
      '@ionic/**', // doesn't get registered in vitest in `server.deps.inline` array
      '@ionic/angular' // does get registered in vitest in `server.deps.inline` array
    ]
  }
})
```

**Closed** 2024-07-31 12:16 UTC
